-- MySQL Script generated by MySQL Workbench
-- Tue Nov 26 20:25:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hallyul
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hallyul` ;

-- -----------------------------------------------------
-- Schema hallyul
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hallyul` DEFAULT CHARACTER SET utf8 ;
USE `hallyul` ;

-- -----------------------------------------------------
-- Table `hallyul`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hallyul`.`usuario` ;

CREATE TABLE IF NOT EXISTS `hallyul`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL UNIQUE,
  `senha` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL UNIQUE,
  `dtnascimento` DATE NOT NULL,
  `tipo` ENUM('GOM', 'GOMllector', 'Collector') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hallyul`.`telefoneUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hallyul`.`telefoneUsuario` ;

CREATE TABLE IF NOT EXISTS `hallyul`.`telefoneUsuario` (
  `idTelefoneUsuario` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(15) NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idTelefoneUsuario`),
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `hallyul`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idUsuario_idx` ON `hallyul`.`telefoneUsuario` (`idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hallyul`.`tipoItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hallyul`.`tipoItem` ;

CREATE TABLE IF NOT EXISTS `hallyul`.`tipoItem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hallyul`.`artista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hallyul`.`artista` ;

CREATE TABLE IF NOT EXISTS `hallyul`.`artista` (
  `idArtista` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` ENUM('Solo', 'Grupo') NOT NULL,
  PRIMARY KEY (`idArtista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hallyul`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hallyul`.`evento` ;

CREATE TABLE IF NOT EXISTS `hallyul`.`evento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` ENUM('Comeback', 'Concerto/Turnê', 'Fan Meeting/Fansign', 'Season\'s Greetings', 'Colaboração com Marca', 'Evento Especial', 'Outros') NOT NULL,
  `idArtista` INT NOT NULL,
  PRIMARY KEY (`id`, `idArtista`),
  CONSTRAINT `fk_evento_artista1`
    FOREIGN KEY (`idArtista`)
    REFERENCES `hallyul`.`artista` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_evento_artista1_idx` ON `hallyul`.`evento` (`idArtista` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hallyul`.`conjunto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hallyul`.`conjunto` ;

CREATE TABLE IF NOT EXISTS `hallyul`.`conjunto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idEvento` INT NOT NULL,
  PRIMARY KEY (`id`, `idEvento`),
  CONSTRAINT `fk_conjunto_evento1`
    FOREIGN KEY (`idEvento`)
    REFERENCES `hallyul`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_conjunto_evento1_idx` ON `hallyul`.`conjunto` (`idEvento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hallyul`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hallyul`.`cart` ;

CREATE TABLE IF NOT EXISTS `hallyul`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `session` VARCHAR(255) NOT NULL,
  `idItem` INT NOT NULL,
  `idLote` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`id`, `session`),
  CONSTRAINT `fk_cart_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `hallyul`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_item`
    FOREIGN KEY (`idItem`)
    REFERENCES `hallyul`.`itemLote` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT `fk_cart_lote1`
    FOREIGN KEY (`idLote`)
    REFERENCES `hallyul`.`itemLote` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cart_usuario1_idx` ON `hallyul`.`cart` (`id` ASC) VISIBLE;

CREATE INDEX `fk_cart_item1_idx` ON `hallyul`.`cart` (`idItem` ASC) VISIBLE;

CREATE INDEX `fk_cart_lote1_idx` ON `hallyul`.`cart` (`idLote` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `hallyul`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hallyul`.`item` ;

CREATE TABLE IF NOT EXISTS `hallyul`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipoItem` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(90) NULL,
  `idConjunto` INT NOT NULL,
  PRIMARY KEY (`id`, `tipoItem`),
  CONSTRAINT `fk_item_tipoItem1`
    FOREIGN KEY (`tipoItem`)
    REFERENCES `hallyul`.`tipoItem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_conjuntoItens1`
    FOREIGN KEY (`idConjunto`)
    REFERENCES `hallyul`.`conjunto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_item_tipoItem1_idx` ON `hallyul`.`item` (`tipoItem` ASC) VISIBLE;

CREATE INDEX `fk_item_conjuntoItens1_idx` ON `hallyul`.`item` (`idConjunto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hallyul`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hallyul`.`compra` ;

CREATE TABLE IF NOT EXISTS `hallyul`.`compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hallyul`.`compraGOM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hallyul`.`compraGOM` ;

CREATE TABLE IF NOT EXISTS `hallyul`.`compraGOM` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCompra` INT NOT NULL,
  `idGOM` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `idCompra`
    FOREIGN KEY (`idCompra`)
    REFERENCES `hallyul`.`compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idGOM`
    FOREIGN KEY (`idGOM`)
    REFERENCES `hallyul`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idCompra_idx` ON `hallyul`.`compraGOM` (`idCompra` ASC) VISIBLE;

CREATE INDEX `idGOM_idx` ON `hallyul`.`compraGOM` (`idGOM` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hallyul`.`lote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hallyul`.`lote` ;

CREATE TABLE IF NOT EXISTS `hallyul`.`lote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCompra` INT NOT NULL,
  `dtCompra` DATE NOT NULL,
  `dtPgto` DATE NULL,
  `pgto` TINYINT NULL,
  PRIMARY KEY (`id`, `idCompra`),
  CONSTRAINT `fk_lote_compra1`
    FOREIGN KEY (`idCompra`)
    REFERENCES `hallyul`.`compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_lote_compra1_idx` ON `hallyul`.`lote` (`idCompra` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hallyul`.`itemLote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hallyul`.`itemLote` ;

CREATE TABLE IF NOT EXISTS `hallyul`.`itemLote` (
  `idItem` INT NOT NULL,
  `idLote` INT NOT NULL,
  `disponibilidade` TINYINT NOT NULL,
  `status` ENUM('Seller', 'Enviado Brasil', 'GOM', 'Enviado collector', 'Collector') NOT NULL,
  `preco` DECIMAL NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idItem`, `idLote`),
  CONSTRAINT `fk_itemLote_item1`
    FOREIGN KEY (`idItem`)
    REFERENCES `hallyul`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemLote_lote1`
    FOREIGN KEY (`idLote`)
    REFERENCES `hallyul`.`lote` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemLote_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `hallyul`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_itemLote_lote1_idx` ON `hallyul`.`itemLote` (`idLote` ASC) VISIBLE;

CREATE INDEX `fk_itemLote_item1_idx` ON `hallyul`.`itemLote` (`idItem` ASC) VISIBLE;

CREATE INDEX `fk_itemLote_usuario1_idx` ON `hallyul`.`itemLote` (`idUsuario` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

DROP USER IF EXISTS hallyulconnection@localhost;
FLUSH PRIVILEGES;
CREATE USER hallyulconnection@localhost IDENTIFIED BY 'connectDatabase';